# Declaring all the constants

# model selection choices
MODEL_CHOICES = ["Hermes LLama 3.1 8B", "Hermes LLama 3.2 3B", "IBM Granite 3.1 8B"]

# custom stopwords for WORDCLOUD
CUSTOM_STOPWORDS = [
    "location",
    "using",
    "said",
    "would",
    "could",
    "also",
    "us",
    "different",
    "create",
    "Aug",
    "Sep",
    "Nov",
    "Dec",
    "Mar",
    "Feb",
    "Jan",
    "May",
    "Jun",
    "support",
    "missing",
    "model",
    "Cloud",
    "Client",
    "application",
    "character",
    "end",
    "call",
    "IND",
    "based",
    "worked",
    "Project",
    "project",
    "model",
    "team",
    "best",
    "Hyderabad",
    "Affine",
    "description",
    "handled",
    "gas",
]

# sections to be extracted from resume
SECTIONS = {
    "Work Experience": [
        "work experience",
        "employment history",
        "professional experience",
        "work history",
        "employment",
        "career history",
        "previous roles",
        "positions held",
        "occupations",
        "job history",
        "professional background",
        "career summary",
        "work summary",
        "experience",
    ],
    "Education": [
        "education",
        "qualifications",
        "academic background",
        "degrees",
        "academic history",
        "educational qualifications",
        "institutes",
        "university",
        "college",
        "school",
        "diplomas",
        "training",
        "courses",
    ],
    "Certifications": [
        "certifications",
        "certificates",
        "certificate",
        "professional certifications",
        "online certifications",
        "courses",
        "online courses",
        "relevant coursework",
        "training programs",
        "workshops",
    ],
    "Skills": [
        "skills",
        "abilities",
        "competencies",
        "proficiencies",
        "technical skills",
        "soft skills",
        "computer skills",
        "language skills",
        "expertise",
        "knowledge",
        "capabilities",
        "strengths",
        "talents",
        "skill set",
    ],
    "Projects": [
        "projects",
        "personal projects",
        "academic projects",
        "portfolio",
        "project experience",
        "project work",
        "key projects",
        "notable projects",
        "independent projects",
        "group projects",
        "research projects",
        "thesis",
        "dissertation",
    ],
    "Awards and Recognition": [
        "awards and recognition",
        "honors and awards",
        "achievements",
        "accolades",
        "awards",
        "honors",
        "recognition",
        "commendations",
        "distinctions",
    ],
    "Volunteer Experience": [
        "volunteer experience",
        "volunteering",
        "community involvement",
        "volunteer work",
        "social work",
        "non-profit work",
        "charity work",
    ],
    "Publications": [
        "publications",
        "published works",
        "articles",
        "papers",
        "books",
        "research papers",
        "conference papers",
        "journal articles",
    ],
    "Interests": [
        "interests",
        "hobbies",
        "extracurricular activities",
        "personal interests",
        "activities",
        "passions",
    ],
    "References": ["references", "references available upon request"],
    "Summary": [
        "summary",
        "objective",
        "professional summary",
        "career objective",
        "career summary",
        "profile",
        "about me",
        "personal profile",
        "overview",
    ],
    "Social Links": [
        "social links",
        "social media",
        "linkedin",
        "github",
        "twitter",
        "facebook",
        "instagram",
        "portfolio website",
        "personal website",
        "online presence",
    ],
    "Personal Information": [
        "personal information",
        "contact information",
        "contact details",
        "address",
        "phone number",
        "email",
        "location",
        "nationality",
    ],
}

# Error message constants
ERROR_MESSAGES = {
    # UI/Interface Errors
    "FILE_NOT_FOUND": "CSS file not found at the specified path",
    "FILE_UPLOAD_REQUIRED": "Please upload a PDF Resume file to Parse",
    "MODEL_SELECTION_ERROR": "Please select a valid model",
    "MULTIPLE_FILES": "Application supports single resume parsing only",
    # File Processing Errors
    "PDF_ONLY": "Only PDF files are supported",
    "FILE_READ_ERROR": "Unable to read the resume file: {}",
    "EMPTY_FILE": "The uploaded file is empty",
    # Resume Parsing Errors
    "PARSE_ERROR": "Error occurred while parsing the resume: {}",
    "EMPTY_TEXT": "No text could be extracted from the resume",
    # Section Extraction Errors
    "EMPTY_SECTION_ERROR": "Failed to extract sections from resume: {}",
    "SKILLS_NOT_FOUND": "Skills section not found in the resume",
    "EXPERIENCE_NOT_FOUND": "Experience details not found in the resume",
    "ENTITIES_EXTRACTION_ERROR": "Failed to extract required entities from SECTION DATA",
    "INCORRECT_FORMAT": "Response expected to be string format but not found",
    "SECTION_PROCESSING_ERROR": "Error while extracting section data {}",
    # API Communication Errors
    "API_ERROR": "Failed to communicate with the server: {}",
    "API_TIMEOUT_ERROR": "Request timed out. Please try again after {} seconds",
    "MULTIPART_ENCODING_ERROR": "Error preparing file for upload: {}",
    # Model Processing Errors
    # "MODEL_ERROR": "Invalid model selection or model not found: {}",
    # "MODEL_LOADING_ERROR": "Failed to load selected model: {}",
    # "MODEL_PROCESSING_ERROR": "Error during model processing: {}",
    # "MODEL_TIMEOUT_ERROR": "Model processing timeout after {} seconds"
    # Analysis & Generation Errors
    "SANITIZATION_ERROR": "Failed to process resume output: {}",
    "WORDCLOUD_ERROR": "Failed to generate word cloud: {}",
    "QUESTION_GENERATION_ERROR": "Failed to generate interview questions: {}",
    # Generic Errors
    "UNEXPECTED_ERROR": "An unexpected error occurred: {}",
    "SERVICE_INIT_ERROR": "Failed to initialize Parser service: {}",
    "RAW_TEXT_SAVE_ERROR": "Error while saving resume text to file: {}",
    "EMPTY_SECTION_ERROR": "Error is extraction section from resume: {}",
    "MODEL_LOAD": "Failed to load SpaCy model: {}",
    "EMPTY_TEXT": "Empty or invalid text provided",
    "SECTION_CHECK": "Section check failed: {}",
}
